### PR TITLE
added new gif 

### PR DESCRIPTION
**Pull request by GregSherman**
new gif added

added a new gif
a new gif was added
for your info, I added one new gif file

### CODE REVIEW

**Comment by taizhng** [comment]
Feeling like it violates the accessibility principle of "what is heck is going on".

Potential change could be making this gif file part of the "two name" series, where the second people value could represent the doorknob.

**Review by eamonma — COMMENTED** [review]
Good comments

**Review by Benson-chou — APPROVED** [review]
yes Good shit

**Review by hisbaan — APPROVED** [review]
Amazing gif

**Review by chen-simon — APPROVED** [review]
:D

**Pull request merged**
